export const GET_APP_NAME = "GET_APP_NAME";
export const FETCH_SUCCESS_NAME = "FETCH_SUCCESS_NAME"
export const GET_APP_DETAIL = "GET_APP_DETAIL"
export const FETCH_SUCCESS_DETAIL = "FETCH_SUCCESS_DETAIL"
export const GET_VALUE = "GET_VALUE"
export const FETCH_SUCCESS_VALUE = "FETCH_SUCCESS_VALUE"